CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	UNIDAD VARCHAR(20) NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	STOCK INT NOT NULL,
	ID_TIPO_PRODUCTO INT NOT NULL
);

CREATE TABLE PROVEEDOR(
	ID_PROVEEDOR INT NOT NULL PRIMARY KEY,
	NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50),
);

ALTER TABLE PEDIDO DROP COLUMN ID_EMPLEADO;
ALTER TABLE PEDIDO ADD ID_USUARIO VARCHAR(50);