USE [DB_PROYECTO_1]
GO

--ALTER TABLE DBO.ROL DROP COLUMN ACTIVO
SELECT *FROM [dbo].[ROL]
/*ALTER TABLE DBO.USUARIO DROP COLUMN ACTIVO*/
SELECT *FROM [dbo].[USUARIO]
--ALTER TABLE DBO.PERMISO DROP COLUMN ACTIVO
SELECT *FROM [dbo].[PERMISO]
--ALTER TABLE DBO.MODULO DROP COLUMN ACTIVO
SELECT *FROM [dbo].[MODULO]


SELECT * FROM [dbo].[AREA]
SELECT *FROM [dbo].[MESA]


SELECT *FROM [dbo].[CLIENTE]

ALTER TABLE DBO.DETALLE_PEDIDO DROP COLUMN OBSERVACION;
SELECT *FROM [dbo].[DETALLE_PEDIDO]



SELECT *FROM [dbo].[MONITORES]

SELECT *FROM [dbo].[PEDIDO]



DROP TABLE DBO.PRODUCTO_COMBO
CREATE TABLE PRODUCTO_COMBO(
	ID_COMBO int NOT NULL,
	TIPO_PRODUCTO int NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	ESTADO INT NOT NULL
);
SELECT *FROM [dbo].[PRODUCTO_COMBO]


CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	UNIDAD VARCHAR(20) NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	STOCK INT NOT NULL,
	ID_TIPO_PRODUCTO INT NOT NULL
);









