CREATE TABLE CATEGORIA_PRODUCTO(
	ID_CATEGORIA_PRODUCTO INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL
);
CREATE TABLE INVENTARIO_DETALLE(
	ID_DETALLE INT NOT NULL PRIMARY KEY,
	PROVEEDOR VARCHAR(50) NOT NULL,
	UNIDAD VARCHAR(50) NOT NULL,
	COSTO_UNIDAD DECIMAL (10,2) NOT NULL,
	CANTIDAD DECIMAL (10,2) NOT NULL
);
CREATE TABLE INVENTARIO_GENERAL(
	CODIGO_PRODUCTO INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL,
	CATEGORIA INT NOT NULL,
	STOCK INT NOT NULL,
	ID_DETALLE INT NOT NULL,
	CONSTRAINT FK_CATEGORIA
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA_PRODUCTO(ID_CATEGORIA_PRODUCTO),
	CONSTRAINT FK_ID_DETALLE
	FOREIGN KEY (ID_DETALLE) REFERENCES INVENTARIO_DETALLE(ID_DETALLE) ON DELETE CASCADE
);



INSERT INTO CATEGORIA_PRODUCTO VALUES (1,'LACTEOS'),
(2,'CARNES'),
(3,'MARISCOS/PESCADOS'),
(4,'FRUTA/VERDURA'),
(5,'REPOSTERIA'),
(6,'BEBIDAS NO ALCOHOLICAS'),
(7,'BEBIDAS ALCOHOLICAS'),
(8,'PRODUCTOS SECOS');
GO

INSERT INTO INVENTARIO_DETALLE VALUES 
(1,'PROCASA','LB',10.5,6),
(2,'PROCASA','LB',25,18),
(3,'WALMART','LT',15.25,6),
(4,'WALMART','KG',10.5,8),
(5,'METAMERCADO','LB',3.5,8),
(6,'METAMERCADO','LB',4,8);

INSERT INTO INVENTARIO_GENERAL VALUES
(1,'CARNE MOLIDA',2,3,1),
(2,'CAMARONES',3,9,2),
(3,'LECHE LIQUIDA',1,4,3),
(4,'QUESO PARMESANO',1,5,4),
(5,'TOMATE',4,3,5),
(6,'PAPA',4,3,6);

SELECT * FROM CATEGORIA_PRODUCTO;
SELECT * FROM INVENTARIO_DETALLE;
SELECT * FROM INVENTARIO_GENERAL;